---
swagger: "2.0"
info:
  description: "FluxNotes Treatment Options Rest Client"
  version: "1.0.1"
  title: "FluxNotes Treatment Options Rest Client"
host: "localhost:3001"
basePath: "/api"
schemes:
- "http"
paths:
  /treatmentOptions:
    get:
      summary: "Get treatment options given filters"
      description: "Return treatment options for the following filters"
      operationId: "findTreatmentOptionsByPatientStats"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "disease"
        in: "query"
        description: "disease filter"
        required: true
        type: "string"
      - name: "Race"
        in: "query"
        description: "race filter"
        required: false
        type: "string"
      - name: "Dx-Grade"
        in: "query"
        description: "grade of disease filter"
        required: false
        type: "string"
      - name: "ageAtDiagnosis"
        in: "query"
        description: "age at diagnosis filter"
        required: false
        type: "string"
      - name: "gender"
        in: "query"
        description: "patient gender filter"
        required: false
        type: "string"
      - name: "stageAtDiagnosis"
        in: "query"
        description: "stage at diagnosis filter"
        required: false
        type: "string"
      - name: "mitosisCount"
        in: "query"
        description: "mitosis count filter"
        required: false
        type: "string"
      - name: "cancerSite"
        in: "query"
        description: "cancer site filer"
        required: false
        type: "string"
      - name: "surgery"
        in: "query"
        description: "surgery recieved filter"
        required: false
        type: "string"
      - name: "pastTreatments"
        in: "query"
        description: "Treatments recieved in past"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "csv"
      - name: "Hemoglobin"
        in: "query"
        description: "lab result for hemoglobin filter"
        required: false
        type: "string"
      - name: "Albumin"
        in: "query"
        description: "lab result for albumin filter"
        required: false
        type: "string"
      - name: "CD117/KIT"
        in: "query"
        description: "immunohistochemical finding"
        required: false
        type: "string"
      - name: "CD34"
        in: "query"
        description: "immunohistochemical finding"
        required: false
        type: "string"
      - name: "Î±-Smooth muscle actin"
        in: "query"
        description: "immunohistochemical finding"
        required: false
        type: "string"
      - name: "desmin"
        in: "query"
        description: "immunohistochemical finding"
        required: false
        type: "string"
      - name: "S-100"
        in: "query"
        description: "immunohistochemical finding"
        required: false
        type: "string"
      - name: "Ki67 index"
        in: "query"
        description: "immunohistochemical finding"
        required: false
        type: "string"
      responses:
        200:
          description: "array of treatment options for given filters"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TreatmentOptions"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "Setting this header to `*` allows all origins. This is\
                \ handy for public REST APIs that don't require authentication. But,\
                \ according to the HTTP spec, browsers *WILL NOT* send cookies if\
                \ this header is `*`, regardless of what you set `Access-Control-Allow-Credentials`\
                \ to.\n"
              default: "*"
        400:
          description: "Invalid filter stats applied"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "Setting this header to `*` allows all origins. This is\
                \ handy for public REST APIs that don't require authentication. But,\
                \ according to the HTTP spec, browsers *WILL NOT* send cookies if\
                \ this header is `*`, regardless of what you set `Access-Control-Allow-Credentials`\
                \ to.\n"
              default: "*"
        404:
          description: "no treatment options found for filters"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "Setting this header to `*` allows all origins. This is\
                \ handy for public REST APIs that don't require authentication. But,\
                \ according to the HTTP spec, browsers *WILL NOT* send cookies if\
                \ this header is `*`, regardless of what you set `Access-Control-Allow-Credentials`\
                \ to.\n"
              default: "*"
      x-swagger-router-controller: "Default"
    options:
      operationId: "treatmentOptionsOPTIONS"
      parameters: []
      responses:
        200:
          description: "Successful Data Retrivial"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "Setting this header to `*` allows all origins. This is\
                \ handy for public REST APIs that don't require authentication. But,\
                \ according to the HTTP spec, browsers *WILL NOT* send cookies if\
                \ this header is `*`, regardless of what you set `Access-Control-Allow-Credentials`\
                \ to.\n"
              default: "*"
        400:
          description: "Invalid Filter applied"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "Setting this header to `*` allows all origins. This is\
                \ handy for public REST APIs that don't require authentication. But,\
                \ according to the HTTP spec, browsers *WILL NOT* send cookies if\
                \ this header is `*`, regardless of what you set `Access-Control-Allow-Credentials`\
                \ to.\n"
              default: "*"
        404:
          description: "Not found"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "Setting this header to `*` allows all origins. This is\
                \ handy for public REST APIs that don't require authentication. But,\
                \ according to the HTTP spec, browsers *WILL NOT* send cookies if\
                \ this header is `*`, regardless of what you set `Access-Control-Allow-Credentials`\
                \ to.\n"
              default: "*"
      x-swagger-router-controller: "Default"
definitions:
  TreatmentOptions:
    type: "object"
    properties:
      isAlive:
        type: "string"
        description: "dead or alive"
      survivalMonths:
        type: "integer"
        format: "int32"
        description: "survival time in months"
      treatOptions:
        type: "string"
        description: "treatment option recieved"
    example:
      isAlive: "isAlive"
      treatOptions: "treatOptions"
      survivalMonths: 0
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
